[tool.black]
line-length = 80
target-version = ['py310']
include = '\.pyi?$'
skip-string-normalization = true

[tool.ruff]
lint.fixable = ["ALL"]
lint.ignore = ["E501"]
lint.select = ["E", "F", "W", "I"]

[tool.isort]
profile = "black"  # Make isort compatible with Black

[tool.mypy]
ignore_missing_imports = true
strict = true  # Enforce type checking

[tool.flake8]
max-line-length = 80
extend-ignore = ["E501"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=app --cov-report=term-missing -v"
asyncio_mode = "auto"

name = "template_project"
version = "0.1.0"
description = "A short description of the project"
authors = ["Eli Lorenzi <elorenzi@terpmail.umd.edu>"]

